name: Release

on:
  push:
    tags:
      - '*'  # Déclenche l’action pour tout tag

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Nécessaire pour récupérer tous les tags Git

      - name: Install GitHub CLI
        run: apt-get install -y gh

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Run make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token GitHub nécessaire pour publier la release
        run: make release
